### ISSUE TITLE
Share Celeb-500k dataset via torrent

### ISSUE THREAD

**Issue by codonna9** [deepinsight/insightface#1451]
Hello,
I'm currently experimenting with robust face recognition algorithms like Subcenter-Arcface. Can anyone, who has the Celeb-500k dataset, share it via torrents? 
Thanks so much in advance!

**Comment by AGenchev** [comment]
Why not use Glint360k ? Authors say this is their best (for 112x112)

**Comment by codonna9** [comment]
Sorry for the late reply. For some unknown reason, I didn't got the notification from github.
Yeah, I downloaded the Glint360k by torrent and I'm very thankful for the authors releasing it. The reason I ask for for Celeb-500k is I'd like to test some new noise-tolerant algorithms to see how far they can push the performance of face recognition models.

**Comment by AGenchev** [comment]
I see this is closed, I can tell you there is a lot of noise in MSCeleb1M as well. Infact I was planning to merge it into VGGFace, but this will destroy opportunity to use LFW as verification dataset, because many celebs are shared between them, e.g. train/test will overlap. Beware the case with glint369k is the same - possible overlapping with LFW.
