### ISSUE TITLE
[arcface_torch] MS1MV3 data iterator error when setting dali=True

### ISSUE THREAD

**Issue by yiminglin-ai** [deepinsight/insightface#2235]
Hi @anxiangsir, @jiankangdeng 
When using the [DALIWarper](https://github.com/deepinsight/insightface/blob/cff32e09218b385933b0583ac49619b5605ee974/recognition/arcface_torch/dataset.py#L230) to iterate over [MS1MV3](https://github.com/deepinsight/insightface/tree/master/recognition/_datasets_#ms1m-retinaface), the following error happens towards the end of iterator: 

```
...
RuntimeError: Critical error in pipeline:
Error when executing Mixed operator decoders__Image encountered:
Error in thread 0: [/opt/dali/dali/operators/decoder/nvjpeg/nvjpeg_decoder_decoupled_api.h:608] [/opt/dali/dali/image/jpeg.cc:126] Assert on "imgcodec::jpeg::GetImageInfo(encoded_buffer, length, &width, &height, &components) == true" failed
...
. File: /tmp/ms1m-retinaface-t1/train.rec at index 29318333604
...
Current pipeline object is no longer valid.
```
The python script I used to do the iteration is 
```python
from dataset import get_dataloader
root_dir = "/tmp/ms1m-retinaface-t1/"
dataloader = get_dataloader(root_dir=root_dir, local_rank=0, batch_size=2048, dali=True, num_workers=4)
for batch in dataloader:
    pass
```

The error suggests that the MS1MV3 rec file seems corrupted, would you be able to generate a new one please? Many thanks!

**Comment by anxiangsir** [comment]
Hello, we have just resolved the issue. This was primarily due to DALI's incompatibility with InsightFace format rec files.

If you want to use DALI for data reading, please use the script `scripts/shuffle_rec.py` to shuffle the InsightFace style rec before using it.

Example:

`python scripts/shuffle_rec.py ms1m-retinaface-t1`

You will get the "shuffled_ms1m-retinaface-t1" folder, where the samples in the "train.rec" file are shuffled.

**Comment by yiminglin-ai** [comment]
Thank you very much for the quick response!
