### ISSUE TITLE
Why are insightface bot links being spammed on discord servers?

### ISSUE THREAD

**Issue by gessyoo** [deepinsight/insightface#2403]
Please instruct your users to stop attempting to install the insightface bot on discord servers where it is not welcome.  The insightface bot links are disruptive, unwanted SPAM and are being reported as such, in every instance.

**Comment by nttstar** [comment]
Can you give the screenshot? I don't quite understand.

**Comment by ArchEight** [comment]
> 

Hello @gessyoo,

I'm Unmoved Mover, the COO and representative of Picsi.Ai - Powered by InsightFace. I sincerely apologize for any inconvenience you've experienced.

To clarify, bots on Discord, including our InsightFace bot, cannot autonomously join any server. They need to be invited by someone with "Manage Server" permissions on a specific server. If our bot is present on any server, it has been added by an administrator or someone with sufficient permissions.

We always advise our users to ensure they have proper permissions and that the community is aligned with the bot's presence and usage. Our bot is specifically designed to respond to user commands and does not spontaneously send messages or promotional links without being triggered.

Your feedback is essential but if you have any specific servers or instances where our bot has caused disruptions, please share those details. We will proactively reach out to those server administrators to understand and address the situation. However, this is not clear to us that this is an issue that is either accurate, or at fault of our bot. We can not censor what people or "our users" do with information, and we will not try.

Best regards,
Unmoved Mover
Chief Operating Officer, Picsi.Ai - Powered by InsightFace

**Comment by gessyoo** [comment]
On Monday, August 14, 2023 at 09:36:42 PM EDT, Jia Guo ***@***.***> wrote:  
 
 

Can you give the screenshot? I don't quite understand.

I would have included a screenshot of the link  -- I assume the visitor was a bot, but the bot link was removed as SPAM.  If the bot links continue to get get dropped in any discord where I am involved, I will screencap the link and post for you.  Here's a screencap of the unwanted invitation, generated by clicking on the link.  Hope this helps you understand what's happening, but these are unwelcome links in discord.

**Comment by ArchEight** [comment]
> On Monday, August 14, 2023 at 09:36:42 PM EDT, Jia Guo ***@***.***> wrote:
> 
> 
> 
> Can you give the screenshot? I don't quite understand.
> 
> I would have included a screenshot of the link  -- I assume the visitor was a bot, but the bot link was removed as SPAM.  If the bot links continue to get get dropped in any discord where I am involved, I will screencap the link and post for you.  Here's a screencap of the unwanted invitation, generated by clicking on the link.  Hope this helps you understand what's happening, but these are unwelcome links in discord.
> 
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.Message ID: ***@***.***>

Hello @gessyoo,

Thank you for your continued communication on this matter.

To reiterate, our bot does not have the ability to independently join servers or send unsolicited messages. If a link related to our bot is present in a server, it has been shared by an individual with the requisite permissions or authority within that server.

We noted that you mentioned a screenshot, but it hasn't been attached to your comments. We're keen to gain a clear understanding of the situation and would appreciate it if you could provide this.

It's essential to understand that while we control the bot's capabilities, we do not, and will not attempt to control every action taken by individual Discord users. If you find inappropriate usage, reporting the specific user responsible for sharing the link is the right course of action. We have since confirmed with Discord that such incidents, if they are indeed occurring, will not impact the standing of our bot or service. So feel free to continue reporting bad actors you feel are spamming, since this is of no fault of, or impact to the Picsi.Ai - Powered by InsightFace - InsightFaceSwap bot.

We hope this clarifies our position.

Best regards,
Unmoved Mover
Chief Operating Officer, Picsi.Ai - Powered by InsightFace

**Comment by nttstar** [comment]
@gessyoo I believe you have some misconceptions about the operation of a Discord server and a Discord bot. Please refer to @ArchEight 's answer.
