### ISSUE TITLE
about the face preprocessing: margin & transformation

### ISSUE THREAD

**Issue by zhenglaizhang** [deepinsight/insightface#29]
Some questions need you guys to help answer, thanks in advance!

- `add fixed margin 44`. 
    - have you guys tried other margin values and see if any improvements?
- `similarity transformation`, 
    - have you guys tried other transformations, I noticed that in `face_preprocess.py` there are some commented code which looks like projective transform.
   - It looks like the similarity transformed image will gain black corner running `test.py`, I use the mtcnn crop the testing images, without resizing and fixed 44 margin. I am not sure if this is by design or I am wrong with the cropping steps -:)  
![0](https://user-images.githubusercontent.com/1740859/35659297-776c0784-0740-11e8-99c4-ab305f8dba13.jpg)
- `mtcnn 5 landmarks`
    - It looks like mtcnn 5 landmarks are not accurate regarding side face, if use more accurate lardmarks, shall it improve the performance?

**Comment by nttstar** [comment]
Face alignment is not the main topic of our current work. We just follow the same pipeline of sphereface: to use 5 landmarks and then do similarity transform. The only difference is we use 112x112 instead of 112x96.  
If your original face image is quite tight, black corners are likely to be happened.
We may provide a 3D-alignment library later, which will be much more accurate.

**Comment by zhenglaizhang** [comment]
@nttstar great, thanks for the detailed info!
