### ISSUE TITLE
requirements.txt

### ISSUE THREAD

**Issue by PawelGD** [deepinsight/insightface#338]
Create requirements.txt file

**Comment by Boeckie** [comment]
Docker file:

#build the docker with
#docker build -t="bartie/insightface_mxnet_python27_gpu:v0.1" .
#
#start the docker with
#docker run --runtime=nvidia -ti -p 9999:9999 bartie/insightface_mxnet_python27_gpu:v0.1 /bin/bash
FROM mxnet/python:nightly_gpu_cu90_mkl_py2

#update and install tooling
RUN apt-get update
#install git
RUN apt-get install -y git
#install wget
RUN apt-get install -y wget
#install unzip
RUN apt-get install -y unzip

#install insightface
RUN git clone  --recursive https://github.com/deepinsight/insightface.git

#download training data MS1M-Arcface
#to download from dropbox, on https://github.com/deepinsight/insightface/wiki/Dataset-Zoo you will find
#the link to dropbox
#in order to download with wget add '?dl=1' at the end of the dropbox download link
#note: the default dropbox link ends with '?dl=0', change '0' into '1'
WORKDIR /mxnet/insightface/datasets
RUN wget -O faces_ms1m-refine-v2_112x112.zip https://www.dropbox.com/s/wpx6tqjf0y5mf6r/faces_ms1m-refine-v2_112x112.zip?dl=1
RUN unzip faces_ms1m-refine-v2_112x112.zip

#install python libs
RUN pip install numpy scipy scikit-learn
RUN pip install easydict
RUN pip install opencv-python
RUN apt-get install -y libglib2.0-0
RUN apt-get install -y libsm6 libxext6 libxrender-dev
RUN pip install pillow    

#install editor
RUN apt-get install -y nano

**Comment by trippycode** [comment]
Even the wget -O faces_ms1m-refine-v2_112x112.zip https://www.dropbox.com/s/wpx6tqjf0y5mf6r/faces_ms1m-refine-v2_112x112.zip?dl=1 is failing.
