### ISSUE TITLE
how did you refine ms1m to get MS1M-refine-v1 and v2 ? thank you!

### ISSUE THREAD

**Issue by guangdongliang** [deepinsight/insightface#513]

**Comment by Neltherion** [comment]
I'd like to know that too since I'm not sure which version to use...

**Comment by Neltherion** [comment]
@nttstar I want to combine MS1M-v2 with my own images to make the model more compatible for other ethnicities.

For example I want the model to be also trained with Middle-Eastern people (Women have lots of more makeup to the point their face structure changes which makes the normal predefined model act poorly sometimes), But I don't know what modifications you did on the MS1M-v2 version of the dataset so that I can modify my training images like them.

**Comment by nttstar** [comment]
face alignment and crop to 112x112.

**Comment by Neltherion** [comment]
@nttstar Thanks!

**Comment by guangdongliang** [comment]
@nttstar there are some refine strategies for dataset cleaning, given the method you used for v2, I can continue refining it because v2 have some obvious noisy.

**Comment by leolordwz** [comment]
> face alignment and crop to 112x112.

@nttstar I downloaded MS1M-IBUG (MS1M-v1) from Dataset Zoo, but cannot find an image list that corresponds to the original dataset. Since we plan to align images using our protocol, could you please share such an image list that can be mapped to the original dataset? Thanks!

**Comment by WeifengOu** [comment]
Since there are many different names regarding different versions of ms1m dataset, below is my own understanding for these different names:
ms1m-v1 = ms1m-ibug
ms1m-v2 = ms1m-arcface
both of them are detected by mtcnn and use the same alignment procedure.

Am I understanding correctly?
