### ISSUE TITLE
MegaFace

### ISSUE THREAD

**Issue by MartinDione** [deepinsight/insightface#52]
Now I believe in order to achieve fairness, you should remove this repository, or at least remove this list of Megaface, because we are working hard to achieve a high result without taking the effort of other R&D guys, Companies... 

Please respect my opinion, I appreciate your work and efforts, but day by day I think to do this thing because after 1 Month we will see all going to have the same result. This is in contrast to previous periods.

**Comment by nttstar** [comment]
It is our promise to open this list to public. MegaFace learderboard is not our final objective but the continous improvement on facial recoginition problem.  You can help us to check this list, and also use this list to do better than us. By the way, NIST vendor test is more convincing.

**Comment by yingfeng** [comment]
Hi, Martin,
Sorry to let you and your company feel uncomfortable. I think the real fairness is to set up a new baseline such that all researchers as well as commertial companies could achieve as optimal as possible regarding to the facial recognition problem.  Although 98% is relative high for the MegaFace challenge, it's not even perfect, for example, the FVRT 2018 challenge is harder than MegaFace since it has 10 times more unique identies, and we do not have enough time to attend that. We'd like to see some one achieve better results.

**Comment by MartinDione** [comment]
Hi guys,

No problem, don't worry. In the near future, we will work together to improve the Facial recognition problems. By the way, you build a good project that will advance the process of the development of such projects. I believe this will work well on FVRT competition especially on the accuracy metric. When we have enough time we will test it on, and we will let you know the result. 

Thank you. You are a super team, and really we appreciate your understanding.
