### ISSUE TITLE
Annotation format for RetinaFace.

### ISSUE THREAD

**Issue by Edwardmark** [deepinsight/insightface#664]
Hi, Thanks for your great work.
But could you tell me what is the annotation format in the labels.txt of RetinaFace?
I noticed that after each lmk point, there is a -1.0/0.0/1.0 what does this value mean? And after each face, there is a float value like 0.82 in the first line of train/labels.txt, what does this value mean?
@nttstar 
Best, Bin

**Comment by Edwardmark** [comment]
Would you kindly please tell me what is the format of labels.txt used in training RetinaFace? Thanks.

**Comment by nttstar** [comment]
Please see ``rcnn/dataset/retinaface.py``

**Comment by cassie101** [comment]
@nttstar, 
I've seen that 0.0 refers to visible, 1.0 refers to invisible, and the last floating point refers to blur.
I have a few questions:
1) How is 'blur' defined, is it based on human annotation or algorithm?
2) How is 'invisible' defined? Because some faces with visible points (for example the second face from left) are also set as 1.0
3) In the paper, you mentioned that there are 5 level of annotatability, I can't find this information in label.txt, is the 'level' provided?

<img src="https://user-images.githubusercontent.com/42600012/57497116-e6c34400-7308-11e9-9287-8f38741eb849.png" height="300">



Thank you!

**Comment by Edwardmark** [comment]
@nttstar @cassie101  Thanks, nttstar, so -1/0/1 denotes the state of unvalid/indisputable/annotatable landmark respectively and the last value means the blur score, is that right?  Did you use the landmark value(0/1) and the blur value in your training?

**Comment by Edwardmark** [comment]
@nttstar Any clue for the -1/0/1 value and its usage in training?
