### ISSUE TITLE
how to train on my own dataset

### ISSUE THREAD

**Issue by ash11sh** [deepinsight/insightface#704]

**Comment by vizakshat** [comment]
Use dir2rec.py to generate data.rec, data.idx and property files. Put them in dataset/emore/ and start the training.

**Comment by Talgin** [comment]
> Use dir2rec.py to generate data.rec, data.idx and property files. Put them in dataset/emore/ and start the training.

**Comment by ash11sh** [comment]
> > Use dir2rec.py to generate data.rec, data.idx and property files. Put them in dataset/emore/ and start the training.
> 
> Hi,
> One more question here... should we have to generate pairs_label.txt, firstly?
> Because, the dir2rec.py requires pairs_label.txt.

go through this thread https://github.com/deepinsight/insightface/issues/682

**Comment by Talgin** [comment]
Hi, 

Sorry again, maybe it's stupid question, but I generated pairs.txt like in the example provided, but we had half (500 rows) of positive and half (500 rows) negative labels. Does the order and numbers somehow affect the result of build_eval_pack.py? I'm asking because we got an error about "Shape of unspecified arg: pre_fc1_weight changed." when running the above module to generate bin file.

**Comment by eeric** [comment]
introduction
https://github.com/eeric/Face_recognition_cnn/blob/main/code/insightface/README.md
