### ISSUE TITLE
@MyraBaba

### ISSUE THREAD

**Issue by Hanson0910** [deepinsight/insightface#760]
@MyraBaba 
hello,i also meet this issue,how did you resolved it
File "/Users/xxx/Projects/new_/insight_10May/insightface/RetinaFace/retinaface.py", line 228, in detect
scores = scores[:, self._num_anchors['stride%s'%s]:, :, :]
IndexError: too many indices for array
please help

_Originally posted by @aneesh0 in https://github.com/deepinsight/insightface/issues/669#issuecomment-503545429_

**Comment by levotrea** [comment]
Hello,

I also had this error when launching test.py with the ResNet50 model that is given in the [Training](https://github.com/deepinsight/insightface/tree/master/RetinaFace#training) section of RetinaFace's README. The error also seems to occur when using the ResNet152 from the Training section.

I solved it by using the [pretrained model](https://www.dropbox.com/s/53ftnlarhyrpkg2/retinaface-R50.zip?dl=0) instead (providied in the [Models](https://github.com/deepinsight/insightface/tree/master/RetinaFace#models) section, just below the Training section). Hope this will help solve your issue as well if you haven't already figured it out by yourself.

**Comment by leo2105** [comment]
Hi @levotrea 

I had the same problem.
This error occurs when you are trying to run mobilenet. For R50 it runs OK.

**Comment by Hanson0910** [comment]
Thank you!


| |
Hanson
|
|
superhan0910@163.com
|
签名由网易邮箱大师定制
On 7/2/2019 05:04，leo2105<notifications@github.com> wrote：

Hi @levotrea

I had the same problem.
This error occurs when you are trying to run mobilenet. For R50 it runs OK.

**Comment by luyao777** [comment]
> Hello,
> 
> I also had this error when launching test.py with the ResNet50 model that is given in the [Training](https://github.com/deepinsight/insightface/tree/master/RetinaFace#training) section of RetinaFace's README. The error also seems to occur when using the ResNet152 from the Training section.
> 
> I solved it by using the [pretrained model](https://www.dropbox.com/s/53ftnlarhyrpkg2/retinaface-R50.zip?dl=0) instead (provided in the [Models](https://github.com/deepinsight/insightface/tree/master/RetinaFace#models) section, just below the Training section). Hope this will help solve your issue as well if you haven't already figured it out by yourself.

Can you give us a more detailed explanation of the modification?

**Comment by levotrea** [comment]
> Can you give us a more detailed explanation of the modification?

Hi @luyao777, 

what worked for me was using the pretrained model, by downloading it from its [Dropbox](https://www.dropbox.com/s/53ftnlarhyrpkg2/retinaface-R50.zip?dl=0), adding it to the insightface models folder (/xxx/insightface-master/models/), and then modifying the "detector" line in test.py so that it now looks like this : `detector = RetinaFace("/xxx/insightface-master/models/retinaface-R50/R50", 0, gpuid, 'net3')` (where "xxx" is meant to be replaced by the absolute path to your insightface-master folder).

But as I said, I got the error when I tried using the ResNet50 model from the training section of the README, so if it is not your case, I can't be sure that this will solve your issue, but I still hope it does.



> Hi @levotrea
> 
> I had the same problem.
> This error occurs when you are trying to run mobilenet. For R50 it runs OK.

Hi @leo2105,

I'm honestly not sure, but I think I wasn't using mobileNet but indeed ResNet50 (or R50) as I mentioned in my first answer, or at least as far as the models are concerned. But I may not have downloaded the right R50 model at first. With the one provided in the Models section of the README it indeed runs smoothly. Thanks for the feedback though.

**Comment by nttstar** [comment]
You may download the wrong models. Pre-trained models under ``Train`` section is just used for training and parameters initialization.

**Comment by levotrea** [comment]
> You may download the wrong models. Pre-trained models under `Train` section is just used for training and parameters initialization.

Okay so this is what I thought. Thank you for the confirmation.

Maybe putting a disclaimer in the README stating that the models in the training section won't work right away with test scripts would help not making this same mistake ?

Because, even though it is logical that the models provided for training actually need to be trained to work, the fact that the `Testing` section is right under the `Training` one (and before the `Models` section) may make it a bit confusing in regards to what model we should use for testing.

In any case, thank you for providing a definite answer.

**Comment by nttstar** [comment]
Thanks, updated.

**Comment by levotrea** [comment]
@Hanson0910,

If your problem is now solved, maybe this issue can be closed ?
