### ISSUE TITLE
What parameters should I change when detecting one single big face in an image with Retinaface?

### ISSUE THREAD

**Issue by buptzyb** [deepinsight/insightface#826]
Hello!

I've tried several images to go through RetinaFace/test.py. I found that for a group photo, it's easy for RetinaFace to detect all faces:

![detector_t1](https://user-images.githubusercontent.com/38978109/62110752-b5dc2500-b2e1-11e9-9ad6-8444b76e2812.jpg)

But when it comes to a single big face in one image as below (which in fact is a crop from a big photo), RetinaFace either fails to detect any faces, or returns a wrong bounding box or landmark.

![detector_t3](https://user-images.githubusercontent.com/38978109/62110753-b5dc2500-b2e1-11e9-8dab-a46c37af999e.jpg)
![detector_t4](https://user-images.githubusercontent.com/38978109/62110754-b674bb80-b2e1-11e9-969d-7a336c22460c.jpg)
![detector_t5](https://user-images.githubusercontent.com/38978109/62110755-b674bb80-b2e1-11e9-9f0e-f22fd444c509.jpg)

I think that this is because some parameters (scale, network, decay4 or something) should be adapt for detecting a big face. In MTCNN, I can feed the whole image into R-Net directly to solve this problem, but I have no idea what to do with RetinaFace. Can anybody help me on this question?

Thank you!

**Comment by israelwei** [comment]
I found that for inference, you can apply resizing and padding to overcome this issue (here I did proportional resizing and padding for getting input with dimensions 640 x 640).
![bigface_test](https://user-images.githubusercontent.com/23454156/62129656-f5a20d00-b2df-11e9-9866-f40c197f9d30.jpg)

**Comment by miracleyoo** [comment]
I encountered this problem too! Testing on big faces(more than half of the whole image, or even slightly larger than image) just cannot be detected or wrongly detected. This will not happen in dlib front face detector. I read the paper and believe this is because the smaller pieces are put more weight in retina face since the pyramid structure is used.  
I believe there can be some way to solve this problem without touching the model. Mainly change the weight for larger features. 
If you have time, I hope you can give me some advice on how to change it. This will be crucial to the real-world applications since there will always be some cases people come closer to the camera. 
@israelwei I think your way is quite practical and I may also try it temporarily, but still this is not clean and decent for an application. Anyway thanks a lot for conforming my guess.
