### ISSUE TITLE
Megaface testing after noise removal

### ISSUE THREAD

**Issue by darshangera** [deepinsight/insightface#863]
Hi,
I followed the script for megaface evaluation and removed images using yours noise removal files. I found not all images mentioned in noise removal.txt were present in feature list.
When I run the code run_experiment.py for evaluation, its fails as many feature files are missing.
Can you please help me in this?

**Comment by songjd** [comment]
use  insightface/Evaluation/Megaface/remove_noises.py

**Comment by Cocoalate** [comment]
hi, could you please tell me when to remove the noise? Should I remove the noise before I extract the features or after?

**Comment by Bryan-bai** [comment]
you can remove the noise after extracted the features

**Comment by Cocoalate** [comment]
> you can remove the noise after extracted the features

I found that the file noise.txt contains the names of noisy images. I wonder why everyone do the removal step after extraction of features.

**Comment by Bryan-bai** [comment]
I think, this is because the label is wrong，which affects the accuracy. 



baijinqiangupc@163.com
 
From: Cocoa
Date: 2020-01-17 15:19
To: deepinsight/insightface
CC: Bryan-bai; Comment
Subject: Re: [deepinsight/insightface] Megaface testing after noise removal (#863)
you can remove the noise after extracted the features
I found that the file noise.txt contains the names of noisy images. I wonder why everyone do the removal step after extraction of features.
