### ISSUE TITLE
compared with facenet

### ISSUE THREAD

**Issue by shenriver** [deepinsight/insightface#940]
I use the same data train with insightface and facenet ,facenet turns out to be better ,so

**Comment by tianxingyzxq** [comment]
Are you kiding me?

**Comment by Johnny-Lin** [comment]
Are you kiding me?

**Comment by adilsarsenov** [comment]
[nice rofl](https://paperswithcode.com/sota/face-verification-on-labeled-faces-in-the
)

**Comment by suman-19** [comment]
Yes facenet is better..:-) 
please don't use innsightface

**Comment by shenriver** [comment]
> Yes facenet is better..:-)
> please don't use innsightface

The purpose of insightface is to promote mxnet, meaningless, not easy to use

**Comment by sudhitpanchal** [comment]
Hi everyone,

I wanted to reopen this discussion since it dates back to 2019. I’ve recently compared **FaceNet** and **Inspireface** models in real-time scenarios, and while I see some differences, I’d love to hear your perspectives.

Why was FaceNet considered better at the time? What issues did you encounter with other models back then? And with the advances since 2019, do you think that conclusion still holds today?

Looking forward to your insights. Thanks!
